itemsFile = open("items.csv", "r", encoding='utf-8-sig')
items = itemsFile.read().splitlines()
itemsFile.close()
langFile = open("../src/main/resources/assets/hyrule/lang/en_us.json", "w")
langFile.write("{\n")
modItemsFile = open("../src/main/java/com/jamesscn/hyrule/init/ModItems.java", "w")
modItemsFile.write("package com.jamesscn.hyrule.init;\n\nimport com.jamesscn.hyrule.HyruleMod;\nimport net.minecraft.item.Item;\nimport net.minecraftforge.registries.ObjectHolder;\n\n@ObjectHolder(HyruleMod.M_ID)\npublic class ModItems {\n")
for i in items:
    itemInfo = i.split(",")
    item = itemInfo[0]
    name = itemInfo[1]
    modelFile = open("../src/main/resources/assets/hyrule/models/item/" + item + ".json", "x")
    modelFile.write("{\n\t\"parent\": \"item/generated\",\n\t\"textures\": {\n\t\t\"layer0\": \"hyrule:item/" + item + "\"\n\t}\n}")
    modelFile.close()
    langFile.write("\t\"item.hyrule." + item + "\": \"" + name + "\",\n")
    modItemsFile.write("\tpublic static final Item " + item + " = null;\n")
langFile.write("\t\"itemGroup.hyrule\": \"The Legend of Hyrule\"\n}")
langFile.close()
modItemsFile.write("}")
modItemsFile.close()